# syntax=docker/dockerfile:1
# read the doc: https://huggingface.co/docs/hub/spaces-sdks-docker
# you will also find guides on how best to write your Dockerfile
FROM node:19 as builder-production

WORKDIR /app

RUN git clone https://github.com/huggingface/chat-ui

WORKDIR /app/chat-ui

RUN npm set cache /app/.npm && npm ci

RUN npm install -g pm2

COPY .env.chatui .env

RUN npm run build

RUN ls

CMD pm2 start /app/build/index.js -i $CPU_CORES --no-daemon